name: docgen
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - fastapi
      - python-multipart
      - pydantic
      - python-docx
      - python-dotenv
      - uvicorn
      - httpx
      - openai
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-auth
      - google-api-python-client
      - Pillow